import:
  - mdolab/.github:travis/jobs-env.yml
  - mdolab/.github:travis/before-install.yml
  - mdolab/.github:travis/install.yml
  - mdolab/.github:travis/script.yml

env:
  global:
    - DOCKER_REPO=public
    - GCC_CONFIG=config/defaults/config.LINUX_GFORTRAN.mk
    - INTEL_CONFIG=config/defaults/config.LINUX_INTEL.mk
    - SEPARATE_COMPLEX_BUILD=true

script:
  - |
    if [ $TEST_TYPE == "docker" ]; then
      # download the regression input files
      docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR/input_files && ./get-input-files.sh"
      # Some of the complex tests take >10 min, so adding travis_wait to stop travis from timing out after 10min
      # the sleep infinity is a workaround since docker exec forks another process which won't work directly with travis_wait
      if [ $DOCKER_TEST_TYPE == "real" ]; then
        # run real tests
        travis_wait 180 sleep infinity & docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR/tests && testflo . -v -n 1";
      elif [ $DOCKER_TEST_TYPE == "complex" ]; then
        # complex tests
        travis_wait 180 sleep infinity & docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR/tests && export PETSC_ARCH=complex-opt-\$COMPILERS-\$PETSCVERSION && testflo . -v -n 1 -m 'cmplx_test_*' ";
      fi
    fi
after_script:
  - docker rm -f app
