os:
  - linux

language: generic

services:
  - docker

env:
  global:
    - REPO_NAME=adflow
    - DOCKER_WORKING_DIR=/home/mdolabuser/repos/$REPO_NAME
    - DOCKER_MOUNT_DIR=/home/mdolabuser/travis/$REPO_NAME
  jobs:
    # We split it into two builds, real and complex to parallelize
    - DOCKER_TAG=py2-latest TEST_TYPE=REAL
    - DOCKER_TAG=py2-latest TEST_TYPE=COMPLEX
    - DOCKER_TAG=py3-stable TEST_TYPE=REAL
    - DOCKER_TAG=py3-stable TEST_TYPE=COMPLEX
    - DOCKER_TAG=py3-latest TEST_TYPE=REAL
    - DOCKER_TAG=py3-latest TEST_TYPE=COMPLEX
    - DOCKER_TAG=py3-impi TEST_TYPE=REAL
    - DOCKER_TAG=py3-impi TEST_TYPE=COMPLEX
    - DOCKER_TAG=py3-centos7-impi TEST_TYPE=REAL
    - DOCKER_TAG=py3-centos7-impi TEST_TYPE=COMPLEX
    

before_install:
  - docker pull mdolab/public:$DOCKER_TAG
  # run Docker, mounting the current Travis directory into Docker to access content of repo
  - docker run -t -d 
        --name app
        --mount "type=bind,src=$(pwd),target=$DOCKER_MOUNT_DIR"
        mdolab/public:$DOCKER_TAG
        /bin/bash

install:
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - docker exec -it app /bin/bash -c "rm -rf $DOCKER_WORKING_DIR && cp -r $DOCKER_MOUNT_DIR $DOCKER_WORKING_DIR"
  # Now download the regression input files
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR/python && wget http://mdolab.engin.umich.edu/sites/default/files/mdolabwebsite/repos/adflow/adflow_input_files.tar.gz && tar -xzf adflow_input_files.tar.gz"
  # Compile real and complex builds
  - if [ "$TEST_TYPE" = "REAL" ]; then
    - if [[ "$DOCKER_TAG" == "py2"* ]]; then
        docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && sed -i 's/python3-config/python-config/g' config/config.mk && make";
      else
        docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && make";
      fi
    else
    - if [[ "$DOCKER_TAG" == "py2"* ]]; then
        docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && sed -i 's/python3-config/python-config/g' config/config.mk && make -f Makefile_CS PETSC_ARCH=complex-opt-\$COMPILERS-\$PETSCVERSION";
      else
        docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk && make -f Makefile_CS PETSC_ARCH=complex-opt-\$COMPILERS-\$PETSCVERSION";
      fi
    fi

script:
  # Some of the complex tests take >10 min, so adding travis_wait to stop travis from timing out after 10min
  # the sleep infinity is a workaround since docker exec forks another process which won't work directly with travis_wait
  - if [ "$TEST_TYPE" = "REAL" ]; then
      travis_wait 120 sleep infinity & docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR/python/reg_tests && python run_reg_tests.py";
    else
      travis_wait 120 sleep infinity & docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR/python/reg_tests && export PETSC_ARCH=complex-opt-\$COMPILERS-\$PETSCVERSION && python run_reg_tests_cs.py";
    fi

after_script:
  - docker rm -f app
